### ISSUE TITLE
Support typed `let` in parsing

### ISSUE THREAD

**Issue by neakor** [uber/needle#117]

**Comment by neakor** [comment]
I think this is already supported. @rudro will verify against his data locally.

**Comment by rudro** [comment]
It is. Closing this out.

FYI, My test was getting confused because the Component class was marked `fileprivate` causing the members to be `fileprivate` and so Needle was ignoring them. Thankfully only about 3 of the Components in our codebase are marked as such.

**Comment by neakor** [comment]
We should probably print out warnings in these cases. I'll open up a separate issue.

**Comment by neakor** [comment]
https://github.com/uber/needle/issues/122
