### ISSUE TITLE
Indicate when a force unwrap/fatalerror is "guarenteed" not to fail

### ISSUE THREAD

**Issue by benpious** [uber/needle#118]
My understanding is that a lot of the force unwraps/fatalerrors in Needle are expected to never crash because the code generator will ensure that they always succeed. 

It would be useful for code reviewers without a lot of context, or for users who might be debugging crashes in Needle, to know which code is guaranteed, and which code is potentially dangerous. 

This could take the form of new method of force unwrapping, for example:
```
extension Optional {
     var guarenteedUnwrap: Wrapped {
          return self!
     }
}
```
Or just be a commitment in the Needle Code Standard (if/when they're written) to only force unwrap when the result is guaranteed to succeed.

**Comment by rudro** [comment]
There are 2 very different sets of force unwrapped uses.

1. In the generated code.  These are quite regular, and (currently) all dumped into a single file.  e.g : https://github.com/uber/needle/blob/master/Generator/Tests/NeedleFrameworkTests/Fixtures/generated.swift

I think the force unwraps here are hopefully easy to understand, and to be exact, you'll see there are only force-casts in that file.

2. There are force unwraps in the Needle generator tool. Some a commented, e.g: https://github.com/uber/needle/blob/784670c019c7a4efa8703a316ada348398c1451e/Generator/Sources/NeedleFramework/Execution/SequenceExecutor.swift#L151
However, there are uses elsewhere that are not so clear. We can certainly make sure every case is clearly documented for starters and then consider the extension.

**Comment by benpious** [comment]
The code I was reading when I made this comment is in NeedleFoundation. Rereading it, I realize that I was more concerned by the large number of guard-fatalErrors in that code, and that the error messages didn't explain whether they should have been prevented automatically or whether the user was responsible for preventing them.
