### ISSUE TITLE
Feature Request: Handle Component extensions

### ISSUE THREAD

**Issue by rudro** [uber/needle#148]
Currently needle does not parse the extensions of a Component.  All your code needs to live in the `FooComponent` class definition. If you have some reason to put some of the vars in a `extension FooComponent` (e.g. you like organizing things this way) then the current version just ignores these properties.

Would be nice if, for all the known Component subclasses, needle considered any extensions made to these subclasses.

**Comment by rudro** [comment]
Note: This is unlikely to make it to the 1.0 release. Would be nice to have this in 1.1.

**Comment by neakor** [comment]
First step #240
