### ISSUE TITLE
Needle should be distributed in a more conventional way

### ISSUE THREAD

**Issue by benpious** [uber/needle#197]
Generally tools aren't distributed through Carthage with binaries checked into a repo. SourceKitten, for example, is distributed on Homebrew.

**Comment by neakor** [comment]
As discussed, I think the current Carthage distribution makes it easy for developers to integrate. SourceKitten isn't exactly the right comparison. Needle has two parts, NeedleFoundation and the generator. SourceKitten doesn't have a SDK component to it. Having said that, I do think giving developers the option to use Homebrew to install the generator is a good idea. We should support that in addition to the current distribution.

**Comment by neakor** [comment]
Also as part of this, we should create a deployment script that performs all the actions at once.

**Comment by neakor** [comment]
Here's the Homebrew PR https://github.com/Homebrew/homebrew-core/pull/34752

**Comment by neakor** [comment]
Needle is now, as of version 0.8.5, distributed via Homebrew as well.
