### ISSUE TITLE
Generated error with different swift code style

### ISSUE THREAD

**Issue by chenjunpu** [uber/needle#224]
When I use [Google Swift Style Guide](https://google.github.io/swift/#column-limit) to write code,  it has a column limit of 100 characters. So i will line-wrapping like [this](https://google.github.io/swift/#line-wrapping) 

```swift
public final class SignInComponent: PluginizedComponent<
  SignInDependency,
  SignInPluginExtension,
  SignInNonCoreComponent
> {
  //...
}
```

But needle can't Recognition these generic arguments, can't generated Dependency Provider code in Factories.

When I write all generic arguments in one line like sample code, it work better.

```swift
public final class SignInComponent: PluginizedComponent<SignInDependency, SignInPluginExtension, SignInNonCoreComponent> {
  //...
}
```

Hope to support different Swift Code Style.
My needle version is v0.8.5.

**Comment by neakor** [comment]
Thanks for filing this issue. We'll address this in the next release. We'll try to get this out with some other planned safety features for the week of Jan 25th.
