### ISSUE TITLE
Rename ComponentType to ComponentProtocol

### ISSUE THREAD

**Issue by ebgraham** [uber/needle#252]
`Type` should be reserved for a generic type, with protocols following proper Swift naming conventions:  https://swift.org/documentation/api-design-guidelines/#protocols-describing-what-is-should-read-as-nouns

```
Protocols that describe what something is should read as nouns (e.g. Collection).

Protocols that describe a capability should be named using the suffixes able, ible, or ing (e.g. Equatable, ProgressReporting).
```

It's confusing to follow Needle's code with `DependencyType` and `ComponentType` (and others) representing different things.

**Comment by neakor** [comment]
Good idea! We can roll this into the next version.
