### ISSUE TITLE
Unable to find a specification for NeedleFoundation

### ISSUE THREAD

**Issue by arueda** [uber/needle#280]
The CocoaPods Specs repo does not have the most recent NeedleFoundation.podspec (v0.9.1) 

This creates a discrepancy on the autogenerated code since Needle Generator will add a reference to NeedleFoundation but CocoaPods will generate Needle.framework

**Comment by woodencoder** [comment]
Same here

**Comment by arueda** [comment]
@woodencoder As a workaround, you can point your pod directly to a commit 
`pod 'NeedleFoundation', :git => 'https://github.com/uber/needle', :commit => 'cd809ff'`

**Comment by woodencoder** [comment]
@arueda oh, right. Thanks!

**Comment by neakor** [comment]
@rudro can you please take a look at this?

**Comment by rudro** [comment]
@woodencoder just pushed 0.9.1 (sorry it took a while, we're still new to publishing pods and ran into some issues).

Please let me know if it's fixed.  Thanks!

**Comment by arueda** [comment]
@rudro It worked for me. Thanks!
