### ISSUE TITLE
Update to Xcode 10.2

### ISSUE THREAD

**Issue by neakor** [uber/needle#283]
This is preventing deployment to homebrew.

https://github.com/Homebrew/homebrew-core/pull/39230

**Comment by neakor** [comment]
Build link https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/41096/version=mojave/testReport/junit/brew-test-bot/mojave/install___build_bottle_needle/

**Comment by neakor** [comment]
Upstream updates https://github.com/uber/swift-common/pull/15

**Comment by norio-nomura** [comment]
https://github.com/jpsim/SourceKitten/pull/587 will not fix the failure of Homebrew's bottling CI for Homebrew/homebrew-core#39230.
For resolving that, it needs to stop using `-Xswiftc -static-stdlib` like https://github.com/jpsim/SourceKitten/pull/582.

**Comment by neakor** [comment]
Thanks @norio-nomura that's really helpful! We'd still like to remove the warnings in our code though. We can continue on the SourceKitten PR.
