### ISSUE TITLE
Unable to run needle generator when installed using brew.

### ISSUE THREAD

**Issue by arueda** [uber/needle#297]
After installing needle generator via brew, I keep receiving the same error message when trying to execute it:
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/needle
  Reason: image not found
Abort trap: 6
```

This is happening on version 0.10.0

When executing the 0.9.1 version installed via Carthage, everything works fine.

**Comment by neakor** [comment]
Seems like your machine is missing the Swift standard lib? I'm not sure if 0.10.0 was built with the standard lib embedded.

**Comment by arueda** [comment]
Installing `Swift 5 Runtime Support for Command Line Tools` from https://support.apple.com/kb/DL1998?locale=en_US. 

Thanks!
