### ISSUE TITLE
Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib

### ISSUE THREAD

**Issue by FranzBusch** [uber/needle#366]
When trying to run needle's latest release 0.16.0 we see an error that it can't find the SwiftSyntaxParser.dylib. The same was happening with mockolo at some point and mockolo is shipping the dylib with its release. The solution is probably to ship the dylib with the releases inside the `Generator/bin` folder. Or do you have another solution in mind?

We are looking forward to using the SwiftSyntaxParser implementation but this currently blocks updating for us.

Mockolo issue: https://github.com/uber/mockolo/issues/108

**Comment by rudro** [comment]
How are you running the `needle` binary? Building from source or using something like `brew install needle`?  @tianskylan is looking in to this right now (we have to deal with the issue for our setup as well)

**Comment by tianskylan** [comment]
@FranzBusch Exactly, shipping the dylib with the binary is probably the best solution. I broke the release yesterday, and will try to fix it today. You are very fast at updating :) Stay tuned.

@rudro I did not publish the update to Homebrew yesterday, knowing that I haven't solved the dylib issue yet.

**Comment by tianskylan** [comment]
v0.16.1 should've fixed the problem.

**Comment by FranzBusch** [comment]
Thanks a lot for the fast response and fix! @tianskylan and @rudro 

We were very happy when we saw your SwiftSyntax migration and wanted to update immediately ;) We were running in a lot of timeout issues before.
