### ISSUE TITLE
Explain the benefits of DI in documentation

### ISSUE THREAD

**Issue by neakor** [uber/needle#39]
Based on single responsibility principle, DI components help encapsulate dependencies.

**Comment by ermik** [comment]
Some proposed notes for the wiki from an innocent bystander:

# What is Needle for?

Needle is Uber's iOS Dependency Injection system. It is a combines a code generator binary with a runtime framework and helps fulfill the needs of individual application components by encapsulating their dependencies.

## What is Dependency Injection?
Dependency Injection is a software design pattern. It describes the way to define a set of dependencies a logic unit of software needs to function, but leaving out any and all actions of satisfying those dependencies to a different, unknown, uncontrolled logic unit that can be a part of the same application or can be external. The unit defining its dependencies is commonly called **the Client**, while the object satisfying those dependencies is called **the Service** (it _services_ the client).

If such service-agnostic (client does not care or care to know about) architecture is established, then _the act of passing_ the Service to the Client is called **Dependency Injection**.

## Why does it matter?
While hardware companies have to deal with Moore's law, large software companies, arguably, live by Conway's law. With that in mind, one can see software architecture patterns that separate concerns, provide runtime safety, and define clear expectations as an extension of human needs described by Dr. Conway.

An organizational principle such as Apple's DRI (Directly Responsible Individual) encapsulates the basic need to have answers, while the party requesting them does not care about the way these answers will have to be assembled. Similarly, a development team does not care for every detail of the management process that defines their scope of work.

**In software**, as in life, it is empowering and liberating to leave out the details of _**how**_ something is to be done, while clearly stating that it _**has to**_ be done. Dependency Injection pattern is a blueprint for doing just that.

**Comment by neakor** [comment]
Thanks so much @ermik This is an awesome starting point for us!

**Comment by neakor** [comment]
And just to add a bit more context for the current stage of this project. Needle is completed and ready for production use. In fact, as we speak, we (Uber) are migrating all of our apps to Needle. This is also why we haven't had the chance to come back and fill in the documentation, examples and guides yet. Once we wrap up Uber's migrations, we'll be sure to come back here and fill in everything for a formal release. I've updated the top-level README with some very crude instructions on how to use Needle right now. Thanks again for your patience.

**Comment by ermik** [comment]
CLA signed by the way. ✅
