### ISSUE TITLE
Bad format of PRODUCT_BUNDLE_IDENTIFIER

### ISSUE THREAD

**Issue by jesus-mg-ios** [uber/needle#391]
Currently, the PRODUCT_BUNDLE_IDENTIFIER of Needle is NeedleFoundation.

We have an error trying to run our application in device because of it. The bundle identifier must to have at least one period (.) to solve this issue.
Ref: https://github.com/Carthage/Carthage/issues/2559#issuecomment-539665460

Could you fix it please?

Have a good day :)

**Comment by didix21** [comment]
@rudro do we have news about this?

**Comment by jesus-qt** [comment]
@tianskylan @mway @brentleyjones

**Comment by jesus-qt** [comment]
@vivekvichare
