### ISSUE TITLE
Provide instructions how to use it

### ISSUE THREAD

**Issue by pbrazdil** [uber/needle#98]
I would love to give it a try and maybe contribute to this project.

How am I suppose to use it? Is there some wiki page or should I look at the code?

Btw, thanks guys, highly appreciated for these efforts.

**Comment by edrew08** [comment]
I would guess that the documentation will be written once the project is out of pre-release mode, but I'm no expert. You can take a look at the sample projects in the sample folder. I was able get the MVC project to build and run without any trouble.

**Comment by neakor** [comment]
@edrew08 is correct. The project is still currently under heavy development. There is no straightforward way to use it yet. We anticipate the initial release to be within a week or two. Thanks for your interest and please be patient with us.

**Comment by neakor** [comment]
@edrew08 I've added some crude instructions on how to use it. We are taking the spare time we have to filling in documentations now.

**Comment by edrew08** [comment]
Thanks @neakor, that's exciting to see. I was able to get Needle to build successfully in a project using Carthage by following the readme directions. 

I did run into one issue that might be a bug in the readme. Originally, when building my app the run script was failing to find the `bin/needle` folder using the provided script. I had to remove the `../` from `../Carthage`.

Original
```
export SOURCEKIT_LOGGING=0 && ../Carthage/Checkouts/needle/Generator/bin/needle generate Sources/NeedleGenerated.swift Sources/ --header-doc ../../copyright_header.txt
```
Updated
```
export SOURCEKIT_LOGGING=0 && Carthage/Checkouts/needle/Generator/bin/needle generate MyApp/NeedleGenerated.swift MyApp/ --header-doc ../../copyright_header.txt
```

**Comment by neakor** [comment]
Please see our documentation now.
